### ISSUE TITLE
when i compile a project am getting error

### ISSUE THREAD

**Issue by rajapandi755** [serglider/shake-detector#1]
Hi am getting this error can you help me.

ERROR in node_modules/shake-detector/types/index.d.ts:7:13 - error TS1005: '=' expected.

7 import type { UserOptions, ShakeHandler } from './types';
              ~
node_modules/shake-detector/types/index.d.ts:7:48 - error TS1005: ';' expected.

7 import type { UserOptions, ShakeHandler } from './types';
                                                 ~~~~~~~~~
node_modules/shake-detector/types/interfaces/IShakeDetector.d.ts:1:13 - error TS1005: '=' expected.

1 import type { ShakeHandler } from '../types';
              ~
node_modules/shake-detector/types/interfaces/IShakeDetector.d.ts:1:35 - error TS1005: ';' expected.

1 import type { ShakeHandler } from '../types';
                                    ~~~~~~~~~~

[ERROR] An error occurred while running subprocess ng.

**Comment by serglider** [comment]
Hey rajapandi755 

I need more info here. Is your project in Typescript or Javascript?

**Comment by rajapandi755** [comment]
Typescript 
Angular 8

**Comment by serglider** [comment]
It seems that the issue is caused by "import type" which was introduced in TS 3.8

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

What is your version of TS?

**Comment by rajapandi755** [comment]
Typescript version 3.4.3

Angular 8.
also am using this plugin to ionic hybrid app, for background shake purpose.

**Comment by serglider** [comment]
Your Typescript version is what causing the issue. As I said above, the "Type-Only Imports" feature was added to TS since 3.8. Is upgrading TS to 3.8 or above is an option for you?

**Comment by rajapandi755** [comment]
No, i have no option to upgrade. this will depending on some other functions. any other way

**Comment by serglider** [comment]
sorry @rajapandi755, but in this case I'd advise you to fork this project and continue from there. I have no plans to downgrade TS
